List quoteslist = [
  '“Who am I helping, what am I breaking, what am I giving, what am I taking?”',
  '“Dostoevsky, too, had lived a dismal and hard life. The czar sent him to a prison camp in Siberia in 1849. Dostoevsky was accused of writing socialist propaganda. He was eventually pardoned and wrote stories to ward off his creditors. Just like in the early ’70s I wrote albums to ward off mine”',
  '“I find C major to be the key of strength, but also the key of regret. E major is the key of confidence. A-flat major is the key of renunciation.”  ',
  '“No martyr is among ye now | Whom you can call your own | So go on your way accordingly | But know you’re not alone.”',
  '“Aretha with no goals, eternally single & one step soft of heaven/ let it be understood that she owns this melody along with her emotional diplomats & her earth & her musical secrets”',
  '“You’ve been through all of F. Scott Fitzgerald’s books, you’re very well read, it’s well known”',
  '“There’s no liquor in the land that can stop your brain from bleedin”',
  '“I say there’re no depressed words just depressed minds.”',
  '“There is nothing so stable as change”',
  '“You’ve got a lotta nerve to say you are my friend. When I was down you just stood there a grinin”',
  '“Privacy is something you can sell, but you can’t buy it back.”',
  '“I can see God in a daisy. I can see God at night in the wind and rain. I see Creation just about everywhere. The highest form of song is prayer. King David’s, Solomon’s, the wailing of a coyote, the rumble of the Earth”',
  '“People are going to say, ‘Well, it’s not very truthful.’ But a songwriter doesn’t care about what’s truthful. What he cares about is what should’ve happened, what could’ve happened. That’s its own kind of truth. It’s like people who read Shakespeare plays, but they never see a Shakespeare play. I think they just use his name.”',
  '“There is no equality. The only thing people all have in common is that they are all going to die.”',
  '“You don’t necessarily have to write to be a poet. Some people work in gas stations and they’re poets. I don’t call myself a poet, because I don’t like the word. I’m a trapeze artist”',
  '“…we are singing today of the WIPE-OUT GANG – the WIPE-OUT GANG buys, owns & operates the Insanity Factory – if you do not know where the Insanity Factory is located, you should hereby take two steps to the right, paint your teeth & go to sleep….”',
  '“I could stay with you forever, and never realize the time”',
  '“I think of a hero as someone who understands the degree of responsibility that comes with his freedom.”',
  '“Passion rules the arrow that flies”',
  '“your problem is that you wanna better word for world”',
  '“People need to be encouraged, not stepped on and put in a straitjacket”',
  '“Act the way you’d like to be and soon you’ll be the way you’d like to act”',
  '“We’re going all the way ’til the wheels fall off and burn”',
  '“I wish that for just one time you could I wish that for just one time you could stand inside my shoes… Then you’d know what a drag it is to see you.”',
  '“I’m just average, common too. I’m just like him and the same as you. I’m everybody’s brother and son. I’m no different than anyone”',
  '“look, you know i don’t wanna come on ungrateful, but that warren report, you know as well as me, just didn’t make it. You know, like they might as well have asked some banana salesman from des moines, who was up in toronto on the big day, if he saw anyone around looking suspicious”',
  '“May you grow up to be righteous, may you grow up to be true. May you always know the truth and see the lights surrounding you. May you always be courageous, stand upright and be strong. May you stay forever young”',
  '“When are you gonna wake up and strengthened the things that remain.”',
  '“I am against nature. I don’t dig nature at all. I think nature is very unnatural. I think the truly natural things are dreams, which nature can’t touch with decay.”',
  '“I almost died because of obesity. It make me cannot breath when sleep at night”',
  '“I think the truly natural things are dreams, which nature can’t touch with decay.”',
  '“If I wanted to be a painter, I might think about trying to be like Van Gogh, or if I was an actor, act like Laurence Olivier. If I was an architect, there’s Frank Gehry. But you can’t just copy somebody. If you like someone’s work, the important thing is to be exposed to everything that person has been exposed to”',
  '“And if you don’t underestimate me, I won’t underestimate you.”',
  '“I accept chaos, I’m not sure whether it accepts me.”',
  '“You learn from a conglomeration of the incredible past – whatever experience gotten in any way whatsoever.”',
  '“You should always take the best from the past, leave the worst back there and go forward into the future.”',
  '“Money doesn’t talk, it swears.”',
  '“What was the future? The future was a solid wall, not promising, not threatening – all bunk. No guarantees of anything, not even the guarantee that life isn’t one big joke.”',
  '“I’ll let you be in my dreams if I can be in yours”',
  '“Couldn’t help but make me feel ashamed to live in a land where justice is a game.”',
  '“Being noticed can be a burden. Jesus got himself crucified because he got himself noticed. So I disappear a lot.”',
  '“The whole world’s a bottle, “”And life’s but a dram, “”When the bottle gets empty, “”It sure ain’t worth a damn.”',
  '“Definition destroys … there’s nothing definite in this world”',
  '“If ever asked to look at yourself, don’t.”',
  '“I saw ten thousand talkers whose tongues were all broken”',
  '“The little room was filled with American records and a phonograph. Izzy would let me stay back there and listen to them. I listened to as many as I could, even thumbed through a lot of his antediluvian folk scrolls. The madly complicated modern world was something I took little interest in. It had no relevancy, no weight. I wasn’t seduced by it”',
  '"Chaos is a friend of mine”',
  '“A million faces at my feet but all I see are dark eyes”',
  '“I wanted to read all these books, but I would have to have been in a rest home or something to do that (p. 37, Chronicles, Vol. One).”',
  '“Todays the day gonna grab my trombone and blow\”” Thunder on the Mountain”',
  '“You can hurt someone and not even know it”',
  '“A man is a success if he gets up in the morning and gets to bed at night, and in between he does what he wants to do”',
  '“It frightens me, the awful truth, of how sweet life can be”',
  '“Some people seem to fade away but then when they are truly gone, it’s like they didn’t fade away at all”',
  '“Every man’s conscience is vile and depraved, you cannot depend on it to be your guide when it’s you who must keep it satisfied”',
  '“It was like he’d been born and raised on Walden Pond where everything was hunky-dory, and I’d come out of the dark demonic woods, same forest, just a different way of looking at things”',
  '“why be bothered with other people’s set-ups? it only leads to torture”',
  '“I had no time for romance. I turned away from the window, from the wintry sun, crossed through the room, went to the stove and made and poured myself a cup of hot chocolate and then clicked on the radio”',
  '“It’s like going out to the desert and screaming and then having little kids throw their sandbox at you. I’m only 24”',
  '“I could be unraveling wherever I’m traveling, even to foreign shores.”',
  '“Let me forget about today until tomorrow”',
  '“If you don’t believe there’s a price for this sweet paradise “”Remind me to show you the scars””',
  '“You’re gonna have to serve somebody; well, it may be the devil, or it may be the Lord, but you’re gonna have to serve somebody.”',
  '“I define nothing. Not beauty, not patriotism. I take each thing as it is, without prior rules about what it should be”',
  '“I’ll let you be in my dreams if I can be in yours”',
  '“The only thing i knew how to do was to keep on keeping on”',
  '“I wanna say hello to all the ex-hippies tonight. I’ve never been a hippie myself but I’m an honorary hippie.”',
  '“The country music stations plays soft but there’s nothing, really nothing to turn off”',
  '“Even if you don’t have all the things you want, be grateful for the things you don’t have that you don’t want (Bob Dylan’s dad)” “',
  '“Behind every beautiful thing, there’s some kind of pain.”',
  '“I was born very far from where I’m supposed to be, and so I’m on my way home.”',
  '“Mona Lisa must have had the highway blues; you can tell by the way she smiles.”',
  '“Inside the museums, | Infinity goes up on trial | Voices echo this is what salvation must be like after a while”',
  '“A poem is a naked person….Some people say that I am a poet”',
  '“It’s east to see without lookin’ too far that not much is really sacred.”',
  '“Without freedom of speech, I might be in the swamp.”',
  '“You don’t need a weatherman to know which way the wind blows.”',
  '“Technology to wipe out truth is now available. Not everybody can afford it but it’s available. When the cost comes down, look out”',
  '“It’s a wicked life, but what the hell, the stars ain’t falling down”',
  '“Once upon a time You dressed so fine”',
  '“To understand you know too soon “”There is no sense in trying”',
  '“You’re born, you know, the wrong names, wrong parents. I mean, that happens. You call yourself what you want to call yourself. This is the land of the free”',
  '“Sweet Goddess, born of a blinding light and a changing wind, don’t be modest – you know who you are and where you’ve been”',
  '“People tell me it’s a sin “”To know and feel too much within”',
  '“I ain’t gonna work on Maggie’s farm no more.”',
  'This land is your land and this land is my land, sure, but the world is run by those that never listen to music anyway”',
  '“I can’t think for you, you’ll have to decide, whether Judas Iscariot had god on his side”',
  '“Little red wagon, little red bike, I ain’t no monkey but I know what I like.”',
  '“There’s only one day at a time here, then it’s tonight and then tomorrow will be today again.”',
  '“If you don’t believe there’s a price for this sweet paradise, just remind me to show you the scars.”',
  '“Democracy don’t rule the world, You’d better get that in your head; This world is ruled by violence “”But I guess that’s better left unsaid”',
  '“The place had an overpowering presence of literature and you couldn’t help but lose your passion for dumbness”',
  '“I think the truly natural things are dreams, which nature cannot touch with decay”',
  '“The rocks on the sand will proudly stand , The hour that the ship comes in.”',
  '“Can you cook and sew, make flowers grow, do you understand my pain? Are you willing to risk it all or is your love in vain?”',
  '“Through the mad mystic hammering of the wild ripping hail the sky cracked its poems in naked wonder, that the clinging of the church bells blew far into the breeze, leaving only bells of lightning and its thunder”',
  '“I’ve got to know that I’m singing something with truth to it. My songs are different than anybody else’s songs. Other artists can get by on their voices and their style, but my songs speak volumes, and all I have to to is lay them down correctly, lyrically, and they’ll do what they need to do.”',
  '“He looked like he came out of nightmare alley.”',
  '“After Lou heard my Guthrie song, he asked me if I ever wrote any songs about baseball players.”',
  '“We all like motorcycles to some degree”',
  '“When you asked me how I was doing, was that some kind of joke”',
  '“If you want to keep your memories, you first have to live them”',
  '“The worth of things can’t be measured by what they cost but by what the cost you to get it, that if anything costs you your faith or your family, then the price is too high, and that there are some things that will never wear out”',
  '“I wasn’t going to go deeper into the darkness for anybody. I was already living in the darkness. My family was my light and I was going to protect that light at all cost. That was where my dedication was, first, last and everything in-between. What did I owe the rest of the world? Nothing. Not a damn thing”',
  '“If my thought-dreams could be seen/ They’d probably put my head in a guillotine”',
  '“Very, very protesty. And, uh, one of the protestiest of all things I ever protested against in my protest years.”',
  '“When I listen to people talk, all I hear is what they’re not tellin’ me.”',
  '“There are men who reach the moon when most of us can not peel off the ground”',
  '“I consider myself a poet first and a musician second. I live like a poet and I’ll die like a poet.”',
  '“It seemed I’d always been chasing after something, anything that moved -a car, a bird, a blowing leaf -anything that might lead me into some more lit place, some unknown land downriver. I had not even the vaguest notion of the broken world I was living in, what society could do with you.”',
  '“I count the years and I shed no tears; I’m blinded to what might have been. Nature’s voice makes my heart rejoice; play me the wild song of the wind.”',
  '“To live outside the law you must be honest.”',
  '“A lot of people don’t have much food on their table. But they got a lot of forks ‘n knives. And they got to cut somethin”',
  '“If I wasn’t Bob Dylan, I’d probably think that Bob Dylan has a lot of answers myself”',
  '“i’ve forgotten more than you’ll ever know”',
  '“If you try to be anyone but yourself, you will fail; if you are not true to your own heart, you will fail. Then again, there’s no success like failure”',
  '“In the dime stores and bus stations/ People talk of situations/ Read books, repeat quotations/ Draw conclusions on the wall”',
  '“All the truth in the world adds up to one big lie”',
  '“I didn’t have any of these dreams or thoughts, but I was going to acquire them.”',
  '“I was born very far from where I’m supposed to be so I’m on my way home.”',
  '“Funny, how the things you have the hardest time parting with are the things you need the least.”',
  '“Well, the comic book and me, just us, we caught the bus.”',
  '“When you feel in your gut what you are and then dynamically pursue it – don’t back down and don’t give up – then you’re going to mystify a lot of folks”',
  '“In the valley of the giants where the stars and stripes explode, the peaches they were sweet and the milk and honey flowed.”',
  '“The inside story on a man was that if he wanted to be successful, he must become a rugged individualist, but then should make some adjustments.”',
  '“We are so scared of losing everything that doesn’t mean anything”',
  '“The ghost of electricity howls in the bones of her face”',
  '“Ain’t it just like the night to play tricks when you’re tryin’ to be so quiet?',
  '“I can identify with other people and situations, but I tend not to. I would rather recall things from my own life, and I don’t have to force myself. . . . Just being in certain environments triggers a response in my brain, a certain feeling I want to articulate. For some reason, I am attracted to self-destruction. I know that personal sacrifice has a great deal to do with how we live or don’t live our lives.”',
  '“It’s a shadowy world, skies are slippery grey. A woman just gave birth to a prince today and dressed him in scarlet. He’ll put the priest in his pocket, put the blade to the heat, take the motherless children off the street and place them at the feet of a harlot.”',
  '“A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.”',
  '“It was a strange world ahead that would unfold, a thunderhead of a world with jagged lightning edges. Many got it wrong and never did get it right. I went straight into it. It was wide open. One thing for sure, not only was it not run by God, but it wasn’t run by the devil either.”',
  '“When You Cease To Exist, Then Who Will You Blame?”',
  '“Remembrance of things past, I do that all the time”',
  '“We sit here stranded, though we’re all doin’ our best to deny it”',
  '“People disagreeing everywhere you look makes you wanna stop and read a book.”',
  '“The pump don’t work cause the vandals took the handle”',
  '“Look at the sun sinkin’ like a ship. Ain’t that just like my heart, babe. When you kissed my lips?”',
  '“Don’t get up gentlemen. I’m only passing through!”',
  '“Life is sad, life is a bust, all you can do is do what you must. You do what you must do, and you do it well”',
  '“There’s always one more notch and four more aces Billy, and you’re playin’ all alon”',
  '“I really was never any more than what I was -a folk musician who gazed into the gray mist with tear-blinded eyes and made up songs that floated in a luminous haze.”',
  '“All i can do is be me, whoever that is”',
  '“Everyone is making love or else expecting rain”',
  '“All I’d ever done was sing songs that were dead straight and expressed powerful new realities. I had very little in common with and knew even less about a generation that I was supposed to be the voice of”',
  '“Well…you know, you can influence all kinds of people, but sometimes it gets in the way — especially if somebody is accusing you of influencing somebody that you had no interest in influencing in the first place”',
  '“You call yourself what you want to call yourself. This is the land of the free”',
  '“I think women rule the world and that no man has ever done anything that a woman either hasn’t allowed him to do or encouraged him to do.”',
  '“Sometimes it’s not enough to know what things mean, sometimes you have to know what things don’t mean.”',
  '“Jesus tapped me on the shoulder and said, ‘Bob, why are you resisting me?’ I said, ‘I’m not resisting You!’ He said, ‘You gonna follow Me?’ I said, ‘I’ve never thought about that before!’ He said, ‘When you’re not following Me. you’re resisiting Me”',
  '“You need something to open up a new door, to show you something you seen before but overlooked a hundred times or more”',
  '“Reality has too many heads”',
  'Well the deputy walks on hard nails and the preacher rides a mount, But nothing really matters much it’s doom alone that counts”',
  '“Last night I danced with a stranger, but she just reminded me you were the one.',
  '“There’s no black and white, left and right to me anymore; there’s only up and down and down is very close to the ground. And I’m trying to go up without thinking about anything trivial such as politics. They have got nothing to do with it. I’m thinking about the general people and when they get hurt.”',
  '“I think of a hero as someone who understands the degree of responsibility that comes with his [and her] freedom.”',
  '“I hate myself for loving you and the weakness that it showed. You were just a painted face on a trip down to suicide road.”',
  '“You better start swimming, or you’ll sink like a stone. Because the Time’s they are a-changing.”',
  '“I’m the oldest son of a crazy man, I’m in a cowboy band.”',
  '“When you think that you lost everything you find out you can always lose a little more.”',
  '“Life is more or less a lie, but then again, that’s exactly the way we want it to be.”',
  '“My big fear was that my guitar would go out of tune”',
  '“I don’t expect politicians to solve anybody’s problems.”',
  '“And songs, to me, were more important than just light entertainment. They were my preceptor and guide into some altered consciousness of reality, some different republic, some liberated republic”',
  '“May your heart always be joyful. May your song always be sung.”',
  '“Be grateful for the things you don’t have that you don’t want”',
  '“People seldom do what they believe in. They do what is convenient, then repent.”',
  '“That he not busy being born is busy dying”',
  '“You can never be wise and be in love at the same time.”',
  '“What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.”',
  '“New York was a city where you could be frozen to death in the midst of a busy street and nobody would notice.”',
  '“They say that patriotism is the last refuge to which a scoundrel clings steal a little and they throw you in jail. Steal a lot and then they make you king”',
  '“I had stood outside of Poe’s house on 3rd street, too, and had done the same thing, staring mournfully up at the windows. The city was like some uncarved block without any name or shape and it showed no favoritism. Everything was always new, always changing. It was never the same old crowd upon the streets.”',
  '“How does it feel, how does it feel to be without a home, like a complete unknown, like a rolling stone”',
  '“When you ain’t got nothin’, you got nothin’ to lose”',
  '“I failed to communicate, that’s why I chose to leave”',
  '“I take each thing as it is, without prior rules about what it should be.”',
  '“Conceit is not necessarily a disease. It’s more of a weakness.”',
  '“I once loved a woman, a child I am told”',
  '“You can always come back, but you can’t come back all the way”',
  '“Every pleasure’s got an edge of pain, pay your ticket and don’t complain”',
  '“If you’re looking to get silly, you better go back to from where you came. because the cops don’t need you and man they expect the same”',
  '“At the final end you won the war after losing every battle.”',
  '“Walkin’ through the leaves fallin’ from the trees, Feelin’ like a stranger nobody sees…”',
  '“I could say that I’d be faithful- I could say it one sweet, easy breath, but to you that would be cruelty and to me it surely would be death.”',
  '“20 years of schooling and they put you on the day shift.”',
  '“Lay down the song you strum”',
  '“How long can I listen to the lies of prejudice? How long can I stay drunk on fear out in the wilderness? Can I cast it aside, all this loyalty and this pride? Will I ever learn that there’ll be no peace, that the war won’t cease, until He returns?”',
  '“DESTINY is a feeling you have that you know something about yourself nobody else does. The picture you have in your own mind of what you’re about WILL COME TRUE. It’s a kind of a thing you kind of have to keep to your own self, because it’s a fragile feeling, and you put it out there, then someone will kill it. It’s best to keep that all inside”',
  '“I like to stay a part of that stuff that don’t change. Actually, it’s not that difficult – people still love and they still hate, they still marry and have children, still slaves in their minds to their desires, still slap each other in the face, and say ‘honey can you turn off the light’ just like they did in ancient Greece. What’s changed? When did Abraham break his father’s idols? I think it was last Tuesday.”',
  '“He not busy being born is busy dying.”',
  '“The world don’t need any more songs… As a matter of fact, if nobody wrote any songs from this day on, the world ain’t gonna suffer for it… There’s enough songs for people to listen to, if they want to listen to songs. For every man, woman and child on earth, they could be sent, probably, each of them, a hundred songs, and never be repeated… Unless someone’s gonna come along with a pure heart and has something to say. That’s a different story”',
  '“All right, I’ll take a chance. I will fall in love with you. If i’m a fool you can have the night, you can have the morning too. Can you cook and sew. make flowers grow. Do you understand my pain? Are you willing to risk it all or is your love in vain?”',
  '“We’ve got to take the world by the horns and solve our own problems. The world owes us nothing, each and every one of us, the world owes us not one single thing. Politicians or whoever.”',
  '“Gonna change my way of thinking, make my self a different set of rules. Gonna put my good foot forward and stop being influenced by fools.”',
  '“People talk of situations, read books, repeat quotations.”',
  '“Wagon Train was on. It seemed to be beaming in from some foreign country. I shut that off, too, and went into another room, a windowless one with a painted door–a dark cavern with a floor-to-ceiling library. I switched on the lamps. The place had an overpowering presence of literature and you couldn’t help but lose your passion for dumbness”',
  '“I never took much, I never asked for your crutch, Now don’t ask for mine.”',
  '““She’s a hypnotist collector; you are a walking antique.”',
  '“Whatever colors you have in your mind, I’ll show them to you and you’ll see them shine”',
  '“Beauty walks a razors edge, someday I’ll make it mine.”',
  '“I just don’t hear anyone else making the music I’m making in my head, so I’ll have to do it myself”',
  '“It’s very tiring having other people tell you how much they dig you if you yourself don’t dig you.”',
  '“The story didn’t make any sense the bible is full of these things. a lot of those old kings and leaders had many wives and concubines and Hosea the prophet was even married to a prostitute and it didn’t stop him for being a holy man”',
  '“Serve God and be cheerful, look upward, beyond, beyond the darkness of masks, the surprises of dawn, in the deep green grasses of the blood-stained world.”',
  '“James Joyce seemed like the most arrogant man who ever lived, had both his eyes wide open and great faculty of speech, but what he say, I knew not what.”',
  '“it ain’t where you’re from, its where you’re going to”',
  '“If love is a sin, then beauty is a crime”',
  '“No one is free, even the birds are chained to the sky.”',
  '“When Johnson started singing, he seemed like a guy who could have sprung from the head of Zeus in full armor”',
  '“Anything worth thinking about is worth singing about.”',
  '“There are many here among us who feel that life is but a joke. But you and I, we’ve been through that, and this is not our fate, so let us not talk falsely now, the hour is getting late”',
  '“I don’t know my why the number 3 is more metaphysically powerful than the number 2, but it is”',
];
